<a href="/users/new">Регистрация</a>

<br>
<?php foreach ($users as $user): ?>
  <div>
    <a href="/users/<?= $user['name'] ?>"><?= htmlspecialchars($user['name']) ?></a>
  </div>
<?php endforeach ?>
<br>
<a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Prev</a> <a href="?page=<?= $page + 1 ?>">Next</a>
<br>
<br>
<br>
<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <input type="submit" value="Search" />
</form>
<br>
<?php foreach ($userSearch as $user): ?>
  <div>
    <a href="/users/<?= $user['name'] ?>"><?= htmlspecialchars($user['name']) ?></a>
  </div>
<?php endforeach ?>