<form action="/users" method="post">
  <div>
    <label>
        Имя : 
      <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name']) ?>">
    </label>
    <?php if (isset($errors['name'])): ?>
      <div><?= $errors['name'] ?></div>
    <?php endif ?>
  </div>
  <br>
  <div>
    <label>
        Email:
      <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
    </label>
    <?php if (isset($errors['email'])): ?>
      <div><?= $errors['email'] ?></div>
    <?php endif ?>
  </div>
  <br>
  <div>
    <label>
        Пароль:
      <input type="password" required name="user[password]" value="<?= htmlspecialchars($user['password']) ?>">
    </label>
    <?php if (isset($errors['password'])): ?>
      <div><?= $errors['password'] ?></div>
    <?php endif ?>
  </div>
  <br>
  <div>
    <label>
        Подтверждение пароля:
      <input type="password" required name="user[passwordConfirmation]" value="<?= htmlspecialchars($user['passwordConfirmation']) ?>">
    </label>
  </div>
  <br>
  <div>
    <label>
      Город
      <select name="user[paid]">
        <option value="">Select</option>
        <option <?= isset($user['city']) && $user['city'] === 3 ? 'selected' : '' ?> value="3">Москва</option>
        <option <?= isset($user['city']) && $user['city'] === 13 ? 'selected' : '' ?> value="3">Пенза</option>
        <option <?= isset($user['city']) && $user['city'] === 399 ? 'selected' : '' ?> value="3">Томск</option>
      </select>
    </label>
    <?php if (isset($errors['city'])): ?>
      <div><?= $errors['city'] ?></div>
    <?php endif ?>
  </div>
  <br>
  <input type="submit" value="Sign Up">
</form>


